# $FreeBSD$

PORTNAME= 	nose_warnings_filters
PORTVERSION=	0.1.1
PORTREVISION=	1
CATEGORIES=	misc devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	gcj21@cl.cam.ac.uk
COMMENT=	Nose plugin to add warnings filters using nose.cfg file

LICENSE=	MIT

RUN_DEPENDS+=	${PYTHON_PKGNAMEPREFIX}nose>0:devel/py-nose

USES+=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
