# $FreeBSD$

PORTNAME=	configparser	
PORTVERSION=	3.5.0
CATEGORIES=	misc devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	gcj21@cl.cam.ac.uk
COMMENT=	This library brings the updated configparser from Python 3.5 \
		to Python 2.6-3.5	

LICENSE=	BSD3CLAUSE

USES+=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
