# $FreeBSD$

PORTNAME=	configparser
PORTVERSION=	3.5.0
PORTREVISION=	1
CATEGORIES=	misc devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	gcj21@cl.cam.ac.uk
COMMENT=	This library brings the configparser from Python 3.5 to 2.6-3.5

LICENSE=	BSD3CLAUSE

USES+=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
